"""
This type stub file was generated by pyright.
"""

from nltk.lm.api import Smoothing

"""Smoothing algorithms for language modeling.

According to Chen & Goodman 1995 these should work with both Backoff and
Interpolation.
"""
def _count_non_zero_vals(dictionary):
    ...

class WittenBell(Smoothing):
    """Witten-Bell smoothing."""
    def __init__(self, vocabulary, counter, discount=..., **kwargs):
        ...
    
    def alpha_gamma(self, word, context):
        ...
    
    def unigram_score(self, word):
        ...
    
    def alpha(self, word, context):
        ...
    
    def gamma(self, context):
        ...
    


class KneserNey(Smoothing):
    """Kneser-Ney Smoothing."""
    def __init__(self, vocabulary, counter, discount=..., **kwargs):
        self.discount = ...
    
    def unigram_score(self, word):
        ...
    
    def alpha_gamma(self, word, context):
        ...
    
    def alpha(self, word, prefix_counts):
        ...
    
    def gamma(self, prefix_counts):
        ...
    


