"""
This type stub file was generated by pyright.
"""

from nltk.corpus.reader.plaintext import PlaintextCorpusReader

"""
UDHR corpus reader. It mostly deals with encodings.
"""
class UdhrCorpusReader(PlaintextCorpusReader):
    ENCODINGS = ...
    SKIP = ...
    def __init__(self, root=...):
        ...
    


