"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

class DrtGlueDemo(object):
    def __init__(self, examples):
        ...
    
    def _init_glue(self):
        ...
    
    def _init_fonts(self, root):
        ...
    
    def _init_exampleListbox(self, parent):
        ...
    
    def _init_readingListbox(self, parent):
        ...
    
    def _populate_readingListbox(self):
        ...
    
    def _init_bindings(self):
        ...
    
    def _init_buttons(self, parent):
        ...
    
    def _configure(self, event):
        ...
    
    def _init_canvas(self, parent):
        ...
    
    def _init_menubar(self, parent):
        ...
    
    def _redraw(self):
        ...
    
    def destroy(self, *e):
        ...
    
    def prev(self, *e):
        ...
    
    def _select_previous_example(self):
        ...
    
    def next(self, *e):
        ...
    
    def _select_next_example(self):
        ...
    
    def about(self, *e):
        ...
    
    def postscript(self, *e):
        ...
    
    def mainloop(self, *args, **kwargs):
        """
        Enter the Tkinter mainloop.  This function must be called if
        this demo is created from a non-interactive program (e.g.
        from a secript); otherwise, the demo will close as soon as
        the script completes.
        """
        ...
    
    def resize(self, size: Optional[Any] = ...):
        ...
    
    def _toggle_remove_duplicates(self):
        ...
    
    def _exampleList_select(self, event):
        ...
    
    def _exampleList_store_selection(self, index):
        ...
    
    def _readingList_select(self, event):
        ...
    
    def _readingList_store_selection(self, index):
        ...
    


class DrsWidget(object):
    def __init__(self, canvas, drs, **attribs):
        self.bbox = ...
    
    def draw(self):
        self.bbox = ...
    
    def clear(self):
        ...
    


def demo():
    ...

if __name__ == '__main__':
    ...
