"""
This type stub file was generated by pyright.
"""

from nltk.cluster.util import VectorSpaceClusterer
from nltk.compat import python_2_unicode_compatible
from typing import Any, Optional

@python_2_unicode_compatible
class GAAClusterer(VectorSpaceClusterer):
    """
    The Group Average Agglomerative starts with each of the N vectors as singleton
    clusters. It then iteratively merges pairs of clusters which have the
    closest centroids.  This continues until there is only one cluster. The
    order of merges gives rise to a dendrogram: a tree with the earlier merges
    lower than later merges. The membership of a given number of clusters c, 1
    <= c <= N, can be found by cutting the dendrogram at depth c.

    This clusterer uses the cosine similarity metric only, which allows for
    efficient speed-up in the clustering process.
    """
    def __init__(self, num_clusters=..., normalise: bool = ..., svd_dimensions: Optional[Any] = ...):
        ...
    
    def cluster(self, vectors, assign_clusters: bool = ..., trace: bool = ...):
        ...
    
    def cluster_vectorspace(self, vectors, trace: bool = ...):
        ...
    
    def _merge_similarities(self, dist, cluster_len, i, j):
        ...
    
    def update_clusters(self, num_clusters):
        ...
    
    def classify_vectorspace(self, vector):
        ...
    
    def dendrogram(self):
        """
        :return: The dendrogram representing the current clustering
        :rtype:  Dendrogram
        """
        ...
    
    def num_clusters(self):
        ...
    
    def __repr__(self):
        ...
    


def demo():
    """
    Non-interactive demonstration of the clusterers with simple 2-D data.
    """
    ...

if __name__ == '__main__':
    ...
